### PR TITLE
Fix broken NX detection

### PR DESCRIPTION
**Pull request by petervas**
Fixed the NX detection that was broken in commit https://github.com/slimm609/checksec.sh/commit/3e5a022dccd4531ae8502022ec9737566acaf790 (See Issue #209).

Commit https://github.com/slimm609/checksec.sh/commit/3e5a022dccd4531ae8502022ec9737566acaf790 replaced the RWE check and only checked the stack size (as described in #132) and that check was not functional because s_readelf was not defined.

Now if GNU_STACK is present then NX is detected as disabled if RWE is found **or** the stack size is not zero.

### CODE REVIEW

**Comment by petervas** [comment]
I fixed the RWE check for NX detection that got lost in the merge [dac2dff](https://github.com/slimm609/checksec.sh/pull/212/commits/dac2dff60344953eb8d8fba70c68140fa9d22d43) and also added it to the process check (i forgot to add it there initially).
Also a minor fix to the output color for the N/A case for NX and RELRO. 

From my point of view the NX fix is good to go now.

**Comment by Artoria2e5** [comment]
Hey, why don't we just throw out `$s_readelf` altogether and just use `$readelf`?

**Comment by petervas** [comment]
> Hey, why don't we just throw out `$s_readelf` altogether and just use `$readelf`?
Initially i just completed the implementation by slimm609 so it would work by adding s_readelf and fixing the nx checks.
But it seems that eu-readelf output is always wide so it would not have worked anyways. 
Removed s_readelf now and changed the NX check to work with readelf and eu-readelf.

**Comment by petervas** [comment]
Fixed the NX check to be able to handle different field sizes in readelf output.
Binaries built for different architectures can have a different readelf output format.

For example 
"GNU_STACK      0x000000 0x00000000 0x00000000 0x00000 0x00000 RW 0x10" 
vs 
"GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RW  0x10"

It would be really helpful to have a test suite to catch all these nuances.

**Comment by petervas** [comment]
Hmm. The failed test seems unrelated to the code changes.

**Pull request closed without merging**
