### PR TITLE
Correct indent in chk_fortify_proc

### PR DESCRIPTION
**Pull request by cgzones**

### CODE REVIEW

**Comment by slimm609** [comment]
can you please pull master into this PR.

**Comment by cgzones** [comment]
rebased

The github diff is a bit weird, but my local `git diff` shows only whitespace changes

**Comment by slimm609** [comment]
👍   I added PR tests to try and wanted to make sure they got picked up properly.  odd that the diff did that.  

Thanks!

**Comment by cgzones** [comment]
Thank you for this very useful tool!

**Pull request merged**
