### PR TITLE
merge open MRs and fix pre-commit

### PR DESCRIPTION
**Pull request by slimm609**
add pre-commit hooks setup

### CODE REVIEW

**Comment by slimm609** [comment]
fixes #190, #191 , #192

**Comment by Maryse47** [comment]
Why was Arch support removed from CI?

**Comment by slimm609** [comment]
Arch support wasn’t removed but testing was removed. Arch does not have json lint and xml lint easily available in pacman and would require compiling the tools.

**Comment by slimm609** [comment]
If they are easily available for testing, it can added back in but there are just missing dependencies that were failing on every PR

**Pull request merged**
